### ISSUE TITLE
Nothing being output

### ISSUE THREAD

**Issue by thomwatson** [MaartenGr/KeyBERT#10]
Hi,

I've tried running this a few different times both locally and on Google Colab. All prerequesites have been installed but whenever I run the example, nothing outputs.

https://colab.research.google.com/drive/1Uv6fHK1FqZN1Z2a4xCeG4_06rXjh7ayu?usp=sharing

Any ideas? Really looking forward to getting this working!

**Comment by MaartenGr** [comment]
I just ran the notebook that you linked to and I am getting results. Make sure that also run `keywords` in a separate cell to see what is contained within that variable. 

I should note that I skipped that first code block as it wasn't necessary.

**Comment by thomwatson** [comment]
Thanks MaartenGr it does, I forgot to run keywords. Works great!

**Comment by Messimeimei** [comment]
when i am doing "kw_model = KeyBERT()",it was just still running but there was no output,what should i do to solve this problem
