### ISSUE TITLE
No module named 'tensorflow.python.keras.engine.keras_tensor'

### ISSUE THREAD

**Issue by DeadWa1ker7** [MaartenGr/KeyBERT#101]
from tensorflow.python.keras.engine.keras_tensor import KerasTensor 
"KerasTensor " can not be found. 
Is it because python, tensorflow and the version of keras do not correspond？

**Comment by MaartenGr** [comment]
That could be the reason but I cannot be entirely sure. Could you share your entire code for installing KeyBERT, the versions in your environment, and the code for running KeyBERT?

**Comment by DeadWa1ker7** [comment]
> That could be the reason but I cannot be entirely sure. Could you share your entire code for installing KeyBERT, the versions in your environment, and the code for running KeyBERT?

code:
```
from keybert import KeyBERT
doc = """
         Supervised learning is the machine learning task of learning a function that
         maps an input to an output based on example input-output pairs.[1] It infers a
         function from labeled training data consisting of a set of training examples.[2]
         In supervised learning, each example is a pair consisting of an input object
         (typically a vector) and a desired output value (also called the supervisory signal).
         A supervised learning algorithm analyzes the training data and produces an inferred function,
         which can be used for mapping new examples. An optimal scenario will allow for the
         algorithm to correctly determine the class labels for unseen instances. This requires
         the learning algorithm to generalize from the training data to unseen situations in a
         'reasonable' way (see inductive bias).
      """
kw_model = KeyBERT()
kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 1))
```

**tensorflow-gpu =2.2.0 keras =2.3.1 python =3.7
CUDA =10.1  cudnn = 7.6.5.32 for windows**

**Comment by MaartenGr** [comment]
In that case, I would try starting from a fresh environment and installing KeyBERT there. It seems to me there are some conflicting dependencies that might cause these issues. Installing in a fresh environment allows some control over these dependencies.
