### ISSUE TITLE
Work with document instead of plain text

### ISSUE THREAD

**Issue by Daanvandam2802** [MaartenGr/KeyBERT#104]
Hey i just started working with KeyBERT so im fairly new to it. I just ran some tests and it works like a charm. I want to have keywords extracted from a document, instead of a chunk of text. But when i try to achieve that, it returns the name of my document. Am I missing something or is there a simple solution I'm forgetting to implement?

**Comment by MaartenGr** [comment]
Could you share the code you have been using? KeyBERT should extract the keywords from the document and not necessarily the name of the document (unless that name is in the document itself). Also, could you share the version you have been using of KeyBERT and its dependencies?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. However, if you want to continue this discussion, please let me know and I'll make sure to re-open this.
