### ISSUE TITLE
Fine tune underlying model with domain specific data

### ISSUE THREAD

**Issue by Tsadoq** [MaartenGr/KeyBERT#107]
First of all, congratulations for your work, it is wonderful.

I was wondering, how should I proceed if i wanted to fine tune the underlying BERT on texts that are relative to the domain I'm going to use the model on? should I have similar sentences? do you any snippet of code to share to do so?

I was thinking of using [this approach](https://www.sbert.net/examples/unsupervised_learning/SimCSE/README.html) to fine tune the model (my data is not labeled).

thank you again

**Comment by MaartenGr** [comment]
> I was wondering, how should I proceed if i wanted to fine tune the underlying BERT on texts that are relative to the domain I'm going to use the model on?

That depends on the domain itself and the output you are already getting from using the base model. Although domain-specific data can be troublesome, this is not always the case. The default SBERT model is trained on quite a lot of data and works well as a baseline on many different domains. Having said that, if you have very specific texts that are related to a domain you are certain the model is not familiar with, then fine-tuning might be worthwhile. However, fine-tuning is an extensive process that typically requires labeled data for it to work well. Choosing pre-trained models that suit your use case is typically preferred. 

> I was thinking of using [this approach](https://www.sbert.net/examples/unsupervised_learning/SimCSE/README.html) to fine tune the model (my data is not labeled).

From the top of my head, what currently works quite well is [GPL](https://www.sbert.net/examples/domain_adaptation/README.html) but it currently only works in English.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. However, if you want to continue this discussion, please let me know and I'll make sure to re-open this.
