### ISSUE TITLE
Flair support

### ISSUE THREAD

**Issue by Fuyuzora** [MaartenGr/KeyBERT#110]
Hey I was trying to use keybert with flair backend but the demo guide throws the below error:
```
Traceback (most recent call last):
  File "/home/robert/bunker/grafted-backend/grafted-nlp/ner/keybert_model.py", line 12, in <module>
    kw_model = KeyBERT(model=roberta)
  File "/home/robert/miniconda3/envs/grafted/lib/python3.9/site-packages/keybert/model.py", line 33, in __init__
    self.model = SentenceTransformer(model)
  File "/home/robert/miniconda3/envs/grafted/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 71, in __init__
    if os.path.exists(model_name_or_path):
  File "/home/robert/miniconda3/envs/grafted/lib/python3.9/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not TransformerDocumentEmbeddings
```

Seems keybert cannot take a TransformerDocumentEmbeddings directly in the constructor? Please let me know if there is anything I missed, thank you!

More information:
```
Demo:
from flair.embeddings import TransformerDocumentEmbeddings
roberta = TransformerDocumentEmbeddings('roberta-base')
kw_model = KeyBERT(model=roberta)
```
keybert=0.1.3 // latest version for keybert[flair]
flair=0.11.2
sentence-transformers=2.2.0
pytorch=1.11.0
huggingface=0.6.0

**Comment by MaartenGr** [comment]
Wow, it seems that I completely forgot about this issue, my apologies! I just try out an `pip install keybert[flair]` and it seems it is working without any issues. It seems that you are using a very old version of KeyBERT (0.1.3) whilst the current version is 0.5.1. I think upgrading to the newest version would solve your issues!

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. However, if you want to continue this discussion, please let me know and I'll make sure to re-open this.
