### ISSUE TITLE
why Mac m1 can't install KeyBERT package

### ISSUE THREAD

**Issue by niccccccccce** [MaartenGr/KeyBERT#112]
I'm a chinese,When I use KeyBERT with my Mac m1 book,I can't install KeyBERT,could you place give me some advices.

**Comment by MaartenGr** [comment]
Thank you for posting your issue. I would need a bit more information to understand what exactly is happening. You mention that you cannot install KeyBERT on your Mac with M1-chip, do you have an error message stating that it cannot install? In other words, could you show me the code for installing KeyBERT and the logging/errors that follows that?

**Comment by niccccccccce** [comment]
I have a question when using MMR。


First, select the keyword that is most similar to the text, and calculate the similarity between the next keyword in the iteration and the selected keyword. When the cosine value is greater than the threshold, the keyword will be discarded. When I set the threshold to 0, I guessed that only one keyword was extracted, but there were many keywords. Where did I misunderstand it? Please guide me. In addition, my English is not very good, please forgive me, thank you.




秦锦飞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaartenGr/KeyBERT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月14日(星期二) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaartenGr/KeyBERT] why Mac m1 can't install KeyBERT package (Issue #112)





 
Thank you for posting your issue. I would need a bit more information to understand what exactly is happening. You mention that you cannot install KeyBERT on your Mac with M1-chip, do you have an error message stating that it cannot install? In other words, could you show me the code for installing KeyBERT and the logging/errors that follows that?

**Comment by MaartenGr** [comment]
What you are describing is not MMR but the basic structure of KeyBERT. It works as follows, for each word in the text we calculate the cosine similarity of that word with the text. As a result, we now know which words are more similar to the text than others. Based on those similarity scores, we extract the, for example, top 30 words. These are the words that are most similar to the text. Note that there is no threshold selected here. KeyBERT does not have a parameter for selecting a cosine similarity threshold. 

When using MMR, we use the `diversity` parameter to define, on a scale from 0 to 1, how diverse the resulting set of keywords is. The higher the value, the less similar the keywords are to each other. 

Hopefully, this helps a bit!

**Comment by niccccccccce** [comment]
Thank you.




秦锦飞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaartenGr/KeyBERT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月3日(星期天) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaartenGr/KeyBERT] why Mac m1 can't install KeyBERT package (Issue #112)





 
What you are describing is not MMR but the basic structure of KeyBERT. It works as follows, for each word in the text we calculate the cosine similarity of that word with the text. As a result, we now know which words are more similar to the text than others. Based on those similarity scores, we extract the, for example, top 30 words. These are the words that are most similar to the text. Note that there is no threshold selected here. KeyBERT does not have a parameter for selecting a cosine similarity threshold.
 
When using MMR, we use the diversity parameter to define, on a scale from 0 to 1, how diverse the resulting set of keywords is. The higher the value, the less similar the keywords are to each other.
 
Hopefully, this helps a bit!

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. However, if you want to continue this discussion, please let me know and I'll make sure to re-open this.
