### ISSUE TITLE
'candidates' argument not working

### ISSUE THREAD

**Issue by pdhlong** [MaartenGr/KeyBERT#122]
Hi, after the latest update, I can't use the 'candidates' argument anymore. Can you have a look. Thank you
![Screenshot 2022-07-28 153714](https://user-images.githubusercontent.com/59214698/181461373-c0ebc606-0abd-431d-849d-59784d67e66f.png)
.

**Comment by MaartenGr** [comment]
I just checked the code and it indeed seems that it is currently not used. It will take some time to go through this but I'll make sure it gets updated in the next release.

**Comment by pdhlong** [comment]
Looking forward to the release. Thank you for your hard work.

**Comment by MaartenGr** [comment]
I just pushed a commit to the master branch that should fix your issue. You can try it out by installing KeyBERT through the latest commit. I will wait a few weeks to see if other issues pop up and then release an official quick fix.
