### ISSUE TITLE
keybert: Fine tuning custom data with few examples 

### ISSUE THREAD

**Issue by gauravgund** [MaartenGr/KeyBERT#125]
Hi,

@MaartenGr @koaning @artmatsak @kunihik0 
Is there a way to fine-tune keybert with custom labelled data to generate meaningful keywords? Please refer me a way to fine-tune keyword extraction on custom data. Thanks in advance.

Thanks in advance.

**Comment by MaartenGr** [comment]
Fine-tuning is not possible within KeyBERT as it uses pre-trained models for semantic similarity. The pre-trained models can all differ in their architecture as well as their underlying libraries. Having said that, you can fine-tune those models and pass them to KeyBERT. Typically, [this](https://www.sbert.net/docs/training/overview.html) is typically a good place to start training a model.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. However, if you want to continue this discussion or if something is not clear, please let me know!
