### ISSUE TITLE
how to use KeyBERT offline

### ISSUE THREAD

**Issue by jack-gits** [MaartenGr/KeyBERT#126]
as my app server can't access network directly, how to use the keyBert?
could you please give us some suggestions?

**Comment by MaartenGr** [comment]
You would need to load in the embedding model locally instead of automatically downloading it from a server. To do so with the `SentenceTransformers`, you can follow along with [this](https://github.com/UKPLab/sentence-transformers/issues/1336) issue and then pass that model to KeyBERT.

**Comment by jack-gits** [comment]
Great!! thanks for your quick response.
