### ISSUE TITLE
[Suggestions] More modular structure, seed keywords weight

### ISSUE THREAD

**Issue by dopc** [MaartenGr/KeyBERT#127]
Hey Maarten, thanks for this great work.

I suggest that, 

1. instead of one function as `extract_keywords`, there could be two function for extracting embeddings and finding keywords. With this way, one can easily try embedding independent parameters, i.e. seed keywords, mmr etc., without waiting for extracting embeddings again and again.
2. The other one is `seed keywords weight`.

for 2, for example, [this line](https://github.com/MaartenGr/KeyBERT/blob/master/keybert/_model.py#L173) to the below one
```
doc_embedding = np.average(
    [doc_embedding, seed_embeddings], 
    axis=0, 
    weights=[1 - seed_weight, seed_weight]
)
```

BR.

**Comment by MaartenGr** [comment]
Thank you for the suggestions! 

> instead of one function as extract_keywords, there could be two function for extracting embeddings and finding keywords. With this way, one can easily try embedding independent parameters, i.e. seed keywords, mmr etc., without waiting for extracting embeddings again and again.

I am not entirely sure I want to further complicate the API by separating functions. It might be interesting however to somehow merge it into the existing function with additional parameters, although it already has plenty of parameters as is. Moreover, it should be quite fast for experimentation with a small subset of documents but I can imagine wanting to experiment with the entire dataset. I'll have to think about it some more to see if it can be implemented elegantly. 

> The other one is seed keywords weight.

It would indeed be helpful if one could play around with that parameter. Like the above, it would extend the parameter space quite a bit making it less user-friendly to use. It does help that the parameter is clearly related to the `seed_keywords` parameter.

**Comment by dopc** [comment]
Thanks!

**Comment by MaartenGr** [comment]
With the new [v0.7 release](https://github.com/MaartenGr/KeyBERT/releases/tag/v0.7.0), you can now prepare the embeddings beforehand in order to speed up fine-tuning the parameters of your model.

**Comment by dopc** [comment]
Great! Thanks for the update.
