### ISSUE TITLE
deploy by torchserve

### ISSUE THREAD

**Issue by jack-gits** [MaartenGr/KeyBERT#128]
I'm using torchserve for model deployment. 
whether can I deploy the KeyBERT by torchserve? 
can you give some advice?

**Comment by MaartenGr** [comment]
Although I am not that familiar with Torch Serve, I believe you can use the custom backends in KeyBERT to prepare the environment for SentenceTransformers. A quick search found [these](https://yashna-shravani.medium.com/deploying-sbert-in-production-using-torchserve-cc1e438a90d) and [these](https://github.com/pytorch/serve/issues/681) links that might help you get started.

**Comment by jack-gits** [comment]
thanks very much. I know how to start on this.
