### ISSUE TITLE
Apple M1 cannot import KeyBERT

### ISSUE THREAD

**Issue by xxwywzy** [MaartenGr/KeyBERT#132]
hi, when I try to import keybert using `from keybert import KeyBERT`, I get an error as follows:
```bash
zsh: illegal hardware instruction  python
```
Is there any way to correctly launch keyBERT in the Apple M1 context? thanks!
P.S. I am using a macbook pro on MacOS Monterey 12.5.1 with a chip of Apple M1 Pro

![image](https://user-images.githubusercontent.com/8501941/191415963-604dbe99-815f-4c72-89b0-9a4873b504e6.png)

**Comment by xxwywzy** [comment]
I have fixed this problem follwoing this guide to install Tensorflow on M1
https://github.com/mrdbourke/m1-machine-learning-test

**Comment by coder-zc** [comment]
attention please! Maybe the installation failure is not due to anconda, but the Python version.I have never succeeded in Python 3.8. I successfully installed Python 3.9
