### ISSUE TITLE
Create ngrams only for words on the same sentence 

### ISSUE THREAD

**Issue by EsmaeilNourani** [MaartenGr/KeyBERT#137]
Thanks for this great library!
when I try to extract 2-grams using keyphrase_ngram_range=(2,2),  it ignores sentence breaks (i.e '.') and combines the word from the next sentence, 
Is it possible to restrict n-grams to be made using words of a single sentence?

**Comment by MaartenGr** [comment]
That relates to the `CountVectorizer` that is used within KeyBERT. There is a parameter `token_pattern` that you can adjust such that it does not ignore sentence breaks. You can find more about that [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html).

**Comment by EsmaeilNourani** [comment]
Thanks for the reply!
Maybe I'm wrong but the following paragraph from this [link](https://stackoverflow.com/questions/26907309/create-ngrams-only-for-words-on-the-same-line-disregarding-line-breaks-with-sc) is the explanation of my problem

> I know that I can modify the tokenizer pattern by passing token_pattern=someRegex to CountVectorizer. Moreover, I read somewhere that the default regex used is u'(?u)\\b\\w\\w+\\b'. Still, I think this problem is more about the ngram creation than about the tokenizer, as the problem is not that tokens are created without respecting the linebreak but the ngrams.

and the solution suggested there was almost what I want!

```
def bigrams_per_line(doc):
    for ln in doc.split('\n'):
        terms = re.findall(r'\w{2,}', ln)
        for bigram in zip(terms, terms[1:]):
            yield '%s %s' % bigram
cv = CountVectorizer(analyzer=bigrams_per_line)

```
It would be really appreciated if you correct me and if there is a better solution!

**Comment by MaartenGr** [comment]
That seems like it should work! I would advise trying it out yourself on your dataset to see whether that works as intended.
