### ISSUE TITLE
Question: What is the ideal doc size to use?

### ISSUE THREAD

**Issue by RumiAllbert** [MaartenGr/KeyBERT#140]
Hi,
Is there a limit to the doc size that should be used? OR are there any recommendations? Will it be okay to use both long and short documents?

**Comment by MaartenGr** [comment]
> Is there a limit to the doc size that should be used? OR are there any recommendations?

It mostly depends on the embedding model that you use. In the case of SentenceTransformers, then smaller documents on either a sentence or paragraph level would be preferred. If you use something like TF-IDF or Longformer, then longer documents might also work. However, when you use longer documents, BERTopic works best if those longer documents contain only a single topic. If you expect them to contain multiple topics, then I would advise splitting them up into sentences/paragraphs. 

> Will it be okay to use both long and short documents?

If your model can capture both long and short documents, then this should be no problem!

I am currently working on a topic distribution approximation after training which might allow you to quickly model multiple topics in a document but that is still WIP.

**Comment by RumiAllbert** [comment]
Maarten, thank you for the speedy response. I will take what you have said into account. Btw do let me know about topic distribution approximation whenever you get it finished ;)
