### ISSUE TITLE
Prepare embeddings from a large dataset 

### ISSUE THREAD

**Issue by celsofranssa** [MaartenGr/KeyBERT#143]
When extracting keywords passing `all_doc_embeddings` and `all_word_embeddings` as shown in the code snipped below:

```python
keywords = kw_model.extract_keywords(
                                        texts, # a subset of all docs 
                                        doc_embeddings=all_doc_embeddings, 
                                        word_embeddings=all_word_embeddings)

```
`texts` can be a subset of all docs?

And is there an approach to showing a progress bar (using `tqdm` for instance) when [preparing embeddings](https://maartengr.github.io/KeyBERT/guides/quickstart.html#prepare-embeddings) (to estimate the duration)?

**Comment by MaartenGr** [comment]
> texts can be a subset of all docs?

No, since word embeddings are passed unordered it is not possible to pass a subset. Instead, you will have to pass a subset of the documents into `extract_embeddings`. 

> And is there an approach to showing a progress bar (using tqdm for instance) when [preparing embeddings](https://maartengr.github.io/KeyBERT/guides/quickstart.html#prepare-embeddings) (to estimate the duration)?

This depends on the embedding model that you are using. You could fashion the SentenceTransformer backend into one that enables a tqdm-like progress bar like so:

```python
from keybert.backend import BaseEmbedder
from sentence_transformers import SentenceTransformer

class CustomEmbedder(BaseEmbedder):
    def __init__(self, embedding_model):
        super().__init__()
        self.embedding_model = embedding_model

    def embed(self, documents, verbose=True):
        embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
        return embeddings

# Create custom backend
embedding_model = SentenceTransformer("paraphrase-MiniLM-L6-v2")
custom_embedder = CustomEmbedder(embedding_model=embedding_model)

# Pass custom backend to keybert
kw_model = KeyBERT(model=custom_embedder)
```

**Comment by celsofranssa** [comment]
I appreciate your explanation and examples.
Thank you.
