### ISSUE TITLE
Unable to import keyBERT

### ISSUE THREAD

**Issue by MarurSrikanta** [MaartenGr/KeyBERT#147]
I tried in three different environments and am unable to import keyBERT.
Below is the error:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/55192359/206249208-7dd13e19-c3d5-4d2c-801a-af4c91f3ccf8.png">

**Comment by MarurSrikanta** [comment]
I have tried the installation in Google Colab, SageMaker and jupyter notebook in my local machine.

**Comment by MaartenGr** [comment]
You should capitalize the `K` in `KeyBERT`. In other words, the following is correct:

```python
from keybert import KeyBERT
```

and not 

```python
from keybert import keyBERT
```

**Comment by MarurSrikanta** [comment]
Thank you, my issue is resolved now. That looks like a fairly simple mistake now :)
