### ISSUE TITLE
Return weights/scores for keywords?

### ISSUE THREAD

**Issue by oterrier** [MaartenGr/KeyBERT#15]
Hi Maarten
I don't know if it is possible to return for each keyword a kind of relevancy score/weight that could be computed using the cosine distance ?
In that case the returned type of `extract_keywords` will be changed from `List[str]` to `List[tuple[str, float]]`

What do you think?

Best regards
Olivier Terrier

**Comment by MaartenGr** [comment]
Although it should be doable, I wanted to keep the solution as simple as possible without going into too much detail for the users. However, it might be nice to also have an option to also return the similarities. 

I might take some time to look into it as I'll have to change several functions (mmr, max_sum_sim, etc.).

**Comment by MaartenGr** [comment]
@oterrier It took a while but it is finally here! V0.2 returns the similarity score to the document for each keyword.
