### ISSUE TITLE
keybert tokenizer

### ISSUE THREAD

**Issue by Hossein-1991** [MaartenGr/KeyBERT#159]
Hi,

Apparently, Keybert's tokenizer doesn't consider letters (i , a ,...). Is there any way to add them?

**Comment by MaartenGr** [comment]
For that, you would have to look into how the [CountVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) works in sklearn. It allows you to pass in custom tokenizers/analyzers which make it possible to do custom tokenization and define which words are and are not included.

**Comment by Hossein-1991** [comment]
> For that, you would have to look into how the [CountVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) works in sklearn. It allows you to pass in custom tokenizers/analyzers which make it possible to do custom tokenization and define which words are and are not included.

Great.
How can I change tokenizer in Keybert? As far as I know, there is no place to redefine that.

**Comment by MaartenGr** [comment]
There is, you can use the parameter `vectorizer` for that. You can read more about it in the [documentation](https://maartengr.github.io/KeyBERT/guides/countvectorizer.html).

**Comment by Hossein-1991** [comment]
> There is, you can use the parameter `vectorizer` for that. You can read more about it in the [documentation](https://maartengr.github.io/KeyBERT/guides/countvectorizer.html).

Perfect!
As my last question, I have a fine-tuned distilbert model, can I use its parameters?

**Comment by MaartenGr** [comment]
Yes, you can find an overview of different embedding packages for loading in your models [here](https://maartengr.github.io/KeyBERT/guides/embeddings.html).
