### ISSUE TITLE
TypeError: extract_keywords() got an unexpected keyword argument 'keyphrase_length'

### ISSUE THREAD

**Issue by sanket19189** [MaartenGr/KeyBERT#16]
Getting this error while running 
model.extract_keywords(doc, keyphrase_length=2, stop_words=None)

**Comment by MaartenGr** [comment]
Nice catch! I forgot to include the changes in the Readme. It should now be:

```python
model.extract_keywords(doc, keyphrase_ngram_range=(1, 1), stop_words=None)
```

It allows you to set a dynamic size with a min and max length.
