### ISSUE TITLE
custom model

### ISSUE THREAD

**Issue by Hossein-1991** [MaartenGr/KeyBERT#162]
Hi,

I generated a customized model that consists of a bert model plus a classification head (2 fc layers). The model's output is an array of shape (N*C) (N: batch size, C: number of classes). I've fine-tuned it on my dataset. Is it possible to use this model in Keybert?

Thanks.

**Comment by MaartenGr** [comment]
If you have a model that returns document and word embeddings, then you can use it according to the documentation [here](https://maartengr.github.io/KeyBERT/guides/embeddings.html#custom-backend). Your model could be possible if you were to remove the classification head and let it return the embeddings instead. Do note though that fine-tuned SBERT models typically perform best.
