### ISSUE TITLE
Model Benchmark

### ISSUE THREAD

**Issue by radandreicristian** [MaartenGr/KeyBERT#170]
Hi, and thanks for this repository. It's very useful!

I wanted to ask if there are any benchmarks of this approach/method (with any of the embeddings), on the literature datasets like SemEval. 

Thanks :D

**Comment by MaartenGr** [comment]
At the moment, there are no benchmarks of KeyBERT due to its modular nature and derivation of some existing papers. There might be in the future but for now the focus has remained on customization instead which complicates evaluation quite a bit.

**Comment by radandreicristian** [comment]
Thanks for the info. Keep up the great work!
