### ISSUE TITLE
Keywords are all lowercase

### ISSUE THREAD

**Issue by secsilm** [MaartenGr/KeyBERT#184]
Hi, great project first.

I would prefer to keep the original form instead of all lowercase. How can I do that? Thanks.

**Comment by MaartenGr** [comment]
That is a result of the underlying tokenizer. You can find more about that [here](https://maartengr.github.io/KeyBERT/guides/countvectorizer.html).

**Comment by secsilm** [comment]
> That is a result of the underlying tokenizer. You can find more about that [here](https://maartengr.github.io/KeyBERT/guides/countvectorizer.html).

OK, I found it. It's a `CountVectorizer` config. Thanks.
