### ISSUE TITLE
Cohere default model

### ISSUE THREAD

**Issue by sam-frampton** [MaartenGr/KeyBERT#193]
`Error while extracting keywords from text: model not found, make sure the correct model ID was used and that you have access to the model.`

The default model xLarge is longer supported by Cohere python client. Switching model to `command` works as expected.

**Comment by MaartenGr** [comment]
Thanks for sharing this! It indeed should be changed. If you, or anyone else want to create a PR, that would be appreciated.

**Comment by sam-frampton** [comment]
@MaartenGr created small PR

**Comment by MaartenGr** [comment]
Awesome, thanks! I just merged the PR 😄
