### ISSUE TITLE
keyphrase_length is not working

### ISSUE THREAD

**Issue by onetigerr** [MaartenGr/KeyBERT#21]
Hello,
I just copied the code from your readme and got following error:

  File "/Users/vladimir/Work/python/foo/main.py", line 35, in <module>
    keywords = model.extract_keywords(doc, keyphrase_length=3, stop_words=None)
TypeError: extract_keywords() got an unexpected keyword argument 'keyphrase_length'

**Comment by MaartenGr** [comment]
Ah, it seems that it should be `keyphrase_ngram_range`  instead of `keyphrase_length`. I'll make sure to change it in the readme.
