### ISSUE TITLE
can't import keybert

### ISSUE THREAD

**Issue by holidaycuki** [MaartenGr/KeyBERT#216]
When I import keybert, it reports this issue:
ImportError: cannot import name 'is_nltk_available' from 'transformers.utils.import_utils' (/Users/wangting/miniconda3/envs/langchain/lib/python3.10/site-packages/transformers/utils/import_utils.py)
How can I solve this problem?

**Comment by MaartenGr** [comment]
Could you share the complete error message? Also, which version of KeyBERT are you using?

**Comment by holidaycuki** [comment]
<img width="1366" alt="截屏2024-03-15 19 58 44" src="https://github.com/MaartenGr/KeyBERT/assets/35600051/1fc0e06f-1e50-49af-bed1-26b5fb5bf6ac">

The version of KeyBERT is 0.6.0

**Comment by MaartenGr** [comment]
Could you share the complete message? It seems to be missing the beginning and it is also truncated at the right.

**Comment by holidaycuki** [comment]
<img width="1372" alt="截屏2024-03-15 20 29 18" src="https://github.com/MaartenGr/KeyBERT/assets/35600051/6b62c9e7-7ed3-4dfb-802f-244918ff09ff">
<img width="1372" alt="截屏2024-03-15 20 29 37" src="https://github.com/MaartenGr/KeyBERT/assets/35600051/19224cc3-73d3-4002-9b89-0c2b86591a0b">

It is too long. I have cut out the beginging and the right side

**Comment by MaartenGr** [comment]
Does that mean you do not have the issue anymore? If not, please copy-paste the error message. Since the error message is text, you can select it, and copy-paste it here.

**Comment by holidaycuki** [comment]
No, I still have this issue, I think it is the environment issue. Now I can run sucessfully in google colab, so I want to give up solve this issue. Thank you!

**Comment by MaartenGr** [comment]
No problem, glad I could help.
