### ISSUE TITLE
Not able to use gensim

### ISSUE THREAD

**Issue by oloumisarah** [MaartenGr/KeyBERT#218]
When following the documentation on gensim to use word2vec I get the following error:

```  
from keybert.backend import GensimBackend
import gensim.downloader as api

ft = api.load('fasttext-wiki-news-subwords-300')
ft_embedder = GensimBackend(ft)


---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_226449/4228192336.py in <module>
----> 1 from keybert.backend import GensimBackend
      2 import gensim.downloader as api
      3 
      4 ft = api.load('fasttext-wiki-news-subwords-300')
      5 ft_embedder = GensimBackend(ft)

ImportError: cannot import name 'GensimBackend' from 'keybert.backend' (/home/sean/KeyBERT/keybert/backend/__init__.py)
```

does GensimBackend need to be included in __init__?
Also would I just pass ft_embedder as the model to KeyBERT?

**Comment by MaartenGr** [comment]
Is this the full error message? It feels like something is missing here. 

Also, which version of BERTopic are you using?

**Comment by oloumisarah** [comment]
@MaartenGr Yep, this is all I see
![Screenshot 2024-04-01 at 11 39 15 AM](https://github.com/MaartenGr/KeyBERT/assets/33963565/7df84bf4-1070-4bb4-be1a-90ac2f090401)

I also just did `pip3 install keybert[gensim]` , restarted the kernel, and ran it again but the error persists. Are you able to reproduce it?

**Comment by oloumisarah** [comment]
![Screenshot 2024-04-01 at 1 20 52 PM](https://github.com/MaartenGr/KeyBERT/assets/33963565/91f1ca0b-2e1b-4dbd-a4b2-ecdc06ee8418)
This seemed to work but I'm not sure if its the right change:
```
diff --git a/keybert/backend/__init__.py b/keybert/backend/__init__.py
index a600155..de149d4 100644
--- a/keybert/backend/__init__.py
+++ b/keybert/backend/__init__.py
@@ -1,3 +1,4 @@
 from ._base import BaseEmbedder
+from ._gensim import GensimBackend

-__all__ = ["BaseEmbedder"]
+__all__ = ["BaseEmbedder","GensimBackend"]
```

**Comment by MaartenGr** [comment]
Ah right, you do not need to import `GensimBackend`. If you follow along with the [documentation](https://maartengr.github.io/KeyBERT/guides/embeddings.html#gensim) you will notice that `ft` is directly passed to KeyBERT:

```python
import gensim.downloader as api
ft = api.load('fasttext-wiki-news-subwords-300')
kw_model = KeyBERT(model=ft)
```

**Comment by oloumisarah** [comment]
Ah OK. Thanks :) I think I may have been confused because I was looking at the comments here: https://github.com/MaartenGr/KeyBERT/blob/f83430f5542d32cb39212249437e28ffee085667/keybert/backend/_gensim.py#L22
