### ISSUE TITLE
min_df and vectorizer parameters

### ISSUE THREAD

**Issue by predoctech** [MaartenGr/KeyBERT#22]
Maarten thanks for this interesting work.

When trying out extract_keywords I have experimented with different values for the min_df parameter.  By reference to sklearn documentation that seem to control stop-words based of frequency of occurrence in document.  However in my experiment there is no observable difference between the results in using a value of 10 or 100.  Am I missing something of the parameter actually have different meaning?

On the other hand is there a reason why the corresponding max_df parameter is not available?

Another parameter is vectorizer, which seem to allow an instance of Countvectorizer instantiated to be passed into for modelling.  Can you please share the typical scenario when this would be useful?  In particular, is it a possibility to add domain-specific vocabulary to the vecotrizer, such that tokens thus keyword candidates derived by the model will be domain specific? 

Thanks.

**Comment by MaartenGr** [comment]
Thanks! 

The `min_df` parameter relates to the minimum frequency across documents. In other words, this parameter does nothing if you only input a single document. It is used to make the sparse count matrix smaller when extracting keywords for many documents at the same time. So it is no surprise you saw no difference if you only used one document. If you did use multiple documents, then it could similarly be the case that by coincidence, the `min_df` parameter did not remove the words that could reasonably act as keywords. 

The `max_df` parameter is very difficult to use in practice and is preserved for those that have a good understanding of the effect of such a parameter. Instead, I decided to give users the option to use their own CountVectorizer where they could use that parameter or any other for that matter. You can then use that custom CountVectorizer to, for example, change the tokenizer or preprocessor. The preprocessor is a nice tool to be used if you want your keywords in a specific format. 

In theory, the extracted keywords should already be domain-specific as it already takes the entire document into account. Forcing to only use a specific vocabulary is technically possible but requires a different procedure.

**Comment by predoctech** [comment]
The topic of multiple document is intriguing.  During my experiment I just copied couple of paragraphs, all wrapped by "" delimiters, to test out the functions.  I guess by definition that is only one paragraph.  But in order to make meaningful use of KeyBert what is your suggestion for the separation into multiple documents?  For example is there a cap in the number of paragraphs/words in one document above which, it works better for parameters (eg. min_df) to split the passage into multiple documents?  What is the recommended strategy in organizing paragraphs to work with KeyBert?

**Comment by MaartenGr** [comment]
The best strategy here is to actually forget about `min_df`. It is used when submitting multiple documents simultaneously but can result in memory errors due to the size of the resulting count matrix. 

In practice, I would advise iterating over `extract_keywords()` and using a single document each time. That way, you do not have to think about `min_df` whilst still getting the best results. It will take a bit longer though. 

Thus, in practice:

```python
from keybert import KeyBERT

doc_one = """
         Supervised learning is the machine learning task of learning a function that
         maps an input to an output based on example input-output pairs.[1] It infers a
         function from labeled training data consisting of a set of training examples.[2]
         In supervised learning, each example is a pair consisting of an input object
         (typically a vector) and a desired output value (also called the supervisory signal). 
          """

doc_two = """
         A supervised learning algorithm analyzes the training data and produces an inferred function, 
         which can be used for mapping new examples. An optimal scenario will allow for the 
         algorithm to correctly determine the class labels for unseen instances. This requires 
         the learning algorithm to generalize from the training data to unseen situations in a 
         'reasonable' way (see inductive bias).
          """

model = KeyBERT('distilbert-base-nli-mean-tokens')

all_keywords = []
for doc in [doc_one, doc_two]:
    keywords = model.extract_keywords(doc)
    all_keywords.append(keywords)

# Or a one-liner:
keywords = [model.extract_keywords(doc) for doc in [doc_one, doc_two]]
```
