### ISSUE TITLE
Drop support for Python < 3.8

### ISSUE THREAD

**Issue by afuetterer** [MaartenGr/KeyBERT#229]
I suggest giving this project the same treatment as `Bertopic`:

- drop Python 3.6-3.7
- add support for 3.8-3.12

See https://github.com/MaartenGr/BERTopic/issues/1942

**Comment by MaartenGr** [comment]
@afuetterer Thanks, totally agree! Aside from security/support reasons, the number of users using Python < 3.8 is also [low](https://pypistats.org/packages/keybert). If you have the time, a PR would be appreciated.

**Comment by afuetterer** [comment]
Already opened #230.

Migration to `pyproject.toml` as well?

**Comment by MaartenGr** [comment]
@afuetterer Yeah, that would be great. But again, only if you have the time, don't want to ask too much of you 😉

**Comment by afuetterer** [comment]
Sure thing.

Actually even if you don't want to use hatch/hatchling as the build backend. You can use `hatch` to migrate from setup.py to pyproject.toml pretty easily.

```
git clone https://github.com/MaartenGr/KeyBERT.git
cd KeyBERT
hatch new --init
```

Some tweaks here and there, but the basic skeleton is alright. For example it wants to sort keywords alphabetically.

**Comment by afuetterer** [comment]
Done via #230.
