### ISSUE TITLE
pre-commit-hooks: replace black and flake8

### ISSUE THREAD

**Issue by afuetterer** [MaartenGr/KeyBERT#232]
Would you like to change `black` and `flake8` to ruff-format and ruff-lint in your pre-commit-config.yaml?

See https://github.com/MaartenGr/BERTopic/pull/2033

**Comment by MaartenGr** [comment]
Yes! If possible, maintaining similar formats between packages would be preferred as both packages share a similar user base.

**Comment by afuetterer** [comment]
Alright, let me propose a PR then. Will do that soon.
