### ISSUE TITLE
OpenAi api

### ISSUE THREAD

**Issue by mahmawad** [MaartenGr/KeyBERT#233]
Hi, i used to use KeyBERT with llm with no problem.

I try now to use it with OpenAI api but I git this error :

" InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.completion.Completion'> "

code i use :

from keybert import KeyLLM

from keybert.llm import OpenAI
import os
import openai
openai.api_type = "azure"
openai.api_base = "--"
openai.api_version = "--"
openai.api_key = "--"

llm = OpenAI(model="gpt-3.5-turbo", prompt=prompt, chat=True)
kw_model = KeyLLM(llm)
keywords = kw_model.extract_keywords(docs) 

appreciate if you could help me with,

**Comment by MaartenGr** [comment]
There was a fix for this in the main branch but that's annoying to install, so I just released [v0.8.5](https://pypi.org/project/keybert/0.8.5/#history) of KeyBERT that should have this fix. So if you install the newest release of KeyBERT and check that it is indeed 0.8.5, it should work!

**Comment by mahmawad** [comment]
Thanks for your help, I thinks the problem is resolved but I have an issue regarding my OpenAI key since I get it from Azure openai and not directly an openai key, therefore i got this error message :

"""
AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: fc48a386********************d4eb. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
"""

it might be the case that KEybert Backend is not compatible with azure openAI ?

**Comment by MaartenGr** [comment]
I believe you can use the `generator_kwargs` parameter to select the correct Azure engine.
