### ISSUE TITLE
How to use with other languages other than english?

### ISSUE THREAD

**Issue by LeMoussel** [MaartenGr/KeyBERT#24]
I would like to use KeyBert with the French language.
To do this, must I select model and pass it through KeyBERT with model?
Like this:
```
from keybert import KeyBERT
doc = """
L'apprentissage supervisé est la tâche d'apprentissage machine qui consiste à apprendre une fonction qui associe une entrée à une sortie en se basant sur des exemples de paires entrée-sortie [1]. 
Il déduit une fonction à partir de données de formation étiquetées consistant en un ensemble d'exemples de formation.
Dans l'apprentissage supervisé, chaque exemple est une paire constituée d'un objet d'entrée  (généralement un vecteur) et une valeur de sortie souhaitée (également appelée signal de supervision). 
"""
model = KeyBERT(model='MODEL_TO_CHOOSE')
keywords = model.extract_keywords(doc)
```

For the French language:
- Which model do you recommend?
- Is that `xlm-r-bert-base-nli-stsb-mean-tokens `  is a good choice?

**Comment by MaartenGr** [comment]
Yes! Simply use `KeyBERT(model='xlm-r-bert-base-nli-stsb-mean-tokens')` to use the multi-lingual model. There are several models that you could use [here](https://www.sbert.net/docs/pretrained_models.html). However, the model that you referenced is the one I would suggest for any language other than English. 

Also, you are in luck! A few days ago I released the v0.2 of KeyBERT which includes Flair. Flair allows you to, essentially, use any 🤗 transformers model. Thus, if you find any good French model, then you could also use that! 

```python
from keybert import KeyBERT
from flair.embeddings import TransformerDocumentEmbeddings

roberta = TransformerDocumentEmbeddings('roberta-base')
model = KeyBERT(model=roberta)
```

Then, instead of `roberta-base`, you can use any model from [this](https://huggingface.co/models) list.

**Comment by LeMoussel** [comment]
Thank you for your help. I am a beginner with transformer model.
I found these 2 french models 
- [camembert-base](https://huggingface.co/camembert-base) : CamemBERT is a state-of-the-art language model for French based on the RoBERTa model.
- [abhilash1910/french-roberta](https://huggingface.co/abhilash1910/french-roberta) : This is a Masked Language Model trained with Roberta on a small French News Corpus(Leipzig corpora). 

Do you think I can test with these 2 models?

**Comment by MaartenGr** [comment]
Although I have not tested these models myself, I do believe CamemBERT is used quite often for French texts. It should be no problem if you were to use those models. I am quite curious myself what the performance is, so let me know if you find out!

**Comment by LeMoussel** [comment]
If you are interested, I can share in this issue, my code comparing the results of keyword extraction with

- TF/IDF
- Yake
- KeyBert

**Comment by MaartenGr** [comment]
That would be great! I cannot read French well, so I would be dependent on your opinion regarding the quality of the keywords 😄

**Comment by LeMoussel** [comment]
Compare keyword extraction results, in French language, from TF/IDF, Yake, KeyBert: https://gist.github.com/LeMoussel/aa5f7c46c6cb09473e97b20eb2e13cc4
The quality of keywords with KeyBert seems "strange" to me.   🤔

**Comment by MaartenGr** [comment]
Hmmm, it might improve if you increase the `keyphrase_ngram_range` to (1, 3) for example. However, this is exactly what can happen with KeyBERT. It is highly dependent on the underlying embedding model. For that reason, I typically like to use embedding models that are trained mostly for similarity measures, like those used in sentence-transformers (e.g., xlm-r-bert-base-nli-stsb-mean-tokens). 

All in all, it requires some experimentation with models until you find the one best suited to your use-case.
