### ISSUE TITLE
How about adding the supportment of the 'transformers' library from HuggingFace.co?

### ISSUE THREAD

**Issue by SakigamiYang** [MaartenGr/KeyBERT#26]
So we can manage more models by using https://huggingface.co/models.

**Comment by MaartenGr** [comment]
You already can! KeyBERT uses the Flair library which makes use of 🤗 transformers, word embeddings, sentence-transformers, and much more. 

To use these models, simply follow this code:

```python
from keybert import KeyBERT
from flair.embeddings import TransformerDocumentEmbeddings

roberta = TransformerDocumentEmbeddings('roberta-base')
model = KeyBERT(model=roberta)
```

**Comment by SakigamiYang** [comment]
Thanks for answering, 
I think I can't wait to try this feature!
