### ISSUE TITLE
How to use KeyBERT in deployment scenarios? 

### ISSUE THREAD

**Issue by katreparitosh** [MaartenGr/KeyBERT#27]
Hey, 

Great work with KeyBERT.

Could you advise on how we can use this service in production? 

How do we load the saved pre-trained model from storage and set-up an API endpoint?

Regards,
Paritosh

**Comment by MaartenGr** [comment]
Hi Paritosh!

Deployment highly depends on your use-cases and the architecture that you use for deploying it. For example, the deployment procedure can be quite different if you are using Swarmpit vs. Kubernetes or if you are not using Docker. 

Having said that, if you initialize a KeyBERT instance in your deployment procedure then it will download the necessary pre-trained model. Setting up an API endpoint is essentially the same as you would most other end-points. KeyBERT only needs to have a string as input so if you create a Flask/FastAPI instance you would only need an end-point supplying the document.
