### ISSUE TITLE
Using Universal Sentence Encoder as the embedding model for documents/candidate keyphrases

### ISSUE THREAD

**Issue by ssubraveti** [MaartenGr/KeyBERT#28]
Can you suggest a way to use Universal Sentence Encoder, or any custom model for generating document/candidate embeddings, instead of options just from HF/Flair/sentence-transformers? I think in general it would be nice to have the functionality to be able to use MMR/MaxSumSimilarity with a generic model! Let me know if you have any thoughts about this, would love to hear your opinion!

**Comment by MaartenGr** [comment]
Good suggestion! I am currently working on something similar for BERTopic that allows you to use a Base class to construct your own embedding model which should allow you to use USE, FastText, etc. When I am finished with that, I can start implementing it in KeyBERT.

**Comment by MaartenGr** [comment]
@ssubraveti
KeyBERT v0.3 was just released and adds the options to use many different backends but also the usage of candidates generated by other extractors. Follow the documentation [here](https://maartengr.github.io/KeyBERT/) for all changes or follow along with the google colab example:

 [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1OxpgwKqSzODtO3vS7Xe1nEmZMCAIMckX?usp=sharing)
