### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'keyphrase_ngram_range'

### ISSUE THREAD

**Issue by hjing100** [MaartenGr/KeyBERT#33]
Traceback (most recent call last):
  File "test01.py", line 27, in <module>
    roberta = TransformerDocumentEmbeddings('bert-base-chinese',keyphrase_ngram_range=(2, 2), stop_words=None)
TypeError: __init__() got an unexpected keyword argument 'keyphrase_ngram_range'

**Comment by hjing100** [comment]
Traceback (most recent call last):
  File "test01.py", line 27, in <module>
    roberta = TransformerDocumentEmbeddings('bert-base-chinese',keyphrase_ngram_range=2, stop_words=None)
TypeError: __init__() got an unexpected keyword argument 'keyphrase_ngram_range'

**Comment by MaartenGr** [comment]
The parameter `keyphrase_n_gram_range` as well as `stop_words` should not be used in the `TransformerDocumentEmbeddings` class from Flair. You should use it as follows:

```python
from keybert import KeyBERT
from flair.embeddings import TransformerDocumentEmbeddings

roberta = TransformerDocumentEmbeddings('roberta-base')
model = KeyBERT(model=roberta, keyphrase_ngram_range=2, stop_words=None)
````
