### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by abhijithneilabraham** [MaartenGr/KeyBERT#44]
In the documentation
https://maartengr.github.io/KeyBERT/guides/embeddings.html
```
import spacy

nlp = spacy.load("en_core_web_md", exclude=['tagger', 'parser', 'ner', 'attribute_ruler', 'lemmatizer'])

kw_model = KeyBERT(model=document_glove_embeddings)nlp
```

The kw_model is loaded with typo in code. You might wanna consider fixing this.

**Comment by MaartenGr** [comment]
Thanks! This will be fixed in the next release.
