### ISSUE TITLE
Support Chinese?

### ISSUE THREAD

**Issue by dengxingwang** [MaartenGr/KeyBERT#45]
Support Chinese?

**Comment by MaartenGr** [comment]
Yes! Simply choose an embedding model that supports Chinese and you are good to go 😄

**Comment by marijndew** [comment]
With Chinese I think it doesn't work "out of the box." I suspect the model needs spaces between words which Chinese doesn't have. It worked for me after I used spaCy to segment the Chinese into space-separated words. Not sure if that's the proper way to go about it tho.

**Comment by MaartenGr** [comment]
Ah right, I forgot about the tokenizer. You need to make sure you use a Tokenizer in KeyBERT that supports tokenization of Chinese. I suggest installing [`jieba`](https://github.com/fxsjy/jieba) for this:

```python
from sklearn.feature_extraction.text import CountVectorizer
import jieba

def tokenize_zh(text):
    words = jieba.lcut(text)
    return words

vectorizer = CountVectorizer(tokenizer=tokenize_zh)
```

Then, simply pass the vectorizer to your KeyBERT instance:

```python
from keybert import KeyBERT

kw_model = KeyBERT()
keywords = kw_model.extract_keywords(doc, vectorizer=vectorizer)
```

**Comment by MaartenGr** [comment]
I will close this for now seeing as there hasn't been an update. However, feel free to re-open it if you are still experiencing this issue!

**Comment by ttranslit** [comment]
Hello, I'm writing here because I've tried using it with the tokenizer as shown above a month agoo and it worked. However, I tried again yesterday and it gives the following error:

```AttributeError                            Traceback (most recent call last)
Cell In[25], line 2
      1 kw_model = KeyBERT('paraphrase-multilingual-MiniLM-L12-v2')
----> 2 keywords = kw_model.extract_keywords(text, vectorizer=tokenize_zh)
      3 keywords

File /opt/anaconda3/envs/keybert_asia/lib/python3.11/site-packages/keybert/_model.py:146, in KeyBERT.extract_keywords(self, docs, candidates, keyphrase_ngram_range, stop_words, top_n, min_df, use_maxsum, use_mmr, diversity, nr_candidates, vectorizer, highlight, seed_keywords, doc_embeddings, word_embeddings)
    144 # Extract potential words using a vectorizer / tokenizer
    145 if vectorizer:
--> 146     count = vectorizer.fit(docs)
    147 else:
    148     try:

AttributeError: 'function' object has no attribute 'fit'```

Is anything changed?
