### ISSUE TITLE
cannot use without internet connectivity

### ISSUE THREAD

**Issue by jannatTumpa** [MaartenGr/KeyBERT#46]
while using "kw_extractor = KeyBERT('distilbert-base-nli-mean-tokens')", it tries to download a pre-trained model from internet. The code is written in a way that I can not customize to use this while working in a server, where there is no internet connectivity. Is there any way to modify the code so that I can upload the pre-trained model in the server and then load it locally?

**Comment by MaartenGr** [comment]
Fortunately, you already can use it locally! The great thing about using sentence-transformers is that it searches automatically for an embedding model locally. If it cannot find one, it will download the pre-trained model from its servers. Make sure that you set the correct path for sentence-transformers to work. You can find a bit more about that [here](https://github.com/UKPLab/sentence-transformers/issues/888)

You can download the corresponding model [here](https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/) and unzip it. Then, simply use the following to create your embedding model:

```python
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer('path/to/unzipped/model')
```

Then, pass it to KeyBERT:
```python
from keybert import KeyBERT
kw_model = KeyBERT(model=embedding_model)
```

**Comment by jannatTumpa** [comment]
Thanks for your prompt response. It worked for me and I love this!
