### ISSUE TITLE
Spacy's non-transformer models in KeyBERT example code bugs in Anaconda project environment

### ISSUE THREAD

**Issue by MindaugasVaitkus2** [MaartenGr/KeyBERT#47]
From keybert documentation I used code to use Spacy's non-transformer models in KeyBERT with Anaconda project environment.  But I get error, see below code? How to use Spacy models with KeyBERT? Does Anaconda environment matters? I used python 3.8 version.
[https://maartengr.github.io/KeyBERT/guides/embeddings.html](url)

`import spacy

nlp = spacy.load("en_core_web_sm", exclude=['tagger', 'parser', 'ner', 'attribute_ruler', 'lemmatizer'])
kw_model = KeyBERT(model=nlp)`

>    ```
 kw_model = KeyBERT(model=nlp)
  File "C:\Users\User\anaconda3\envs\test\lib\site-packages\keybert\model.py", line 33, in __init__
    self.model = SentenceTransformer(model)
  File "C:\Users\User\anaconda3\envs\test\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 41, in __init__
    if not os.path.isdir(model_path) and not model_path.startswith('http://') and not model_path.startswith('https://'):
  File "C:\Users\User\anaconda3\envs\test\lib\genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not English
```

**Comment by MaartenGr** [comment]
I might be mistaken, but is seems you are using an early version of KeyBERT that does not support Spacy models. Which version are you using of KeyBERT?

**Comment by MindaugasVaitkus2** [comment]
Yes, I used keybert-0.1.3. I tried to update with pip the project, but the version 0.1.3 remained. I uninstalled keybert and then installed again version 0.4.0 and spacy library model works.
