### ISSUE TITLE
`xla_device` argument has been deprecated

### ISSUE THREAD

**Issue by pendekarcode** [MaartenGr/KeyBERT#57]
I found notifications like this:

The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.

My model code:
sentence_model = SentenceTransformer("distilbert-base-nli-stsb-mean-tokens", device="cpu")
kw_model = KeyBERT(model=sentence_model)

Thanks

**Comment by MaartenGr** [comment]
You get this warning since `device="cpu"` in the `SentenceTransformer` class is deprecated. Now, it automatically detects whether you have a cpu or gpu. In other words, you can remove that parameter.

**Comment by pendekarcode** [comment]
Hi @MaartenGr Thanks for this.
