### ISSUE TITLE
Obtained keywords 

### ISSUE THREAD

**Issue by lfoppiano** [MaartenGr/KeyBERT#59]
Hi, 
   in the documentation it seems that the returned keywords are tuples with keyword value and weight: 
```
kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 1), stop_words=None)
[('learning', 0.4604),
 ('algorithm', 0.4556),
 ('training', 0.4487),
 ('class', 0.4086),
 ('mapping', 0.3700)]
```

However, when I run it I get just a list of keywords: 
```
['fermi', 'tungsten', 'superconducting', 'superconductors', ...
```

Are these keywords ordered by any criteria? I mean, if I fetch the top 5 but then I'm interested in the most "important" one, may I just pick up the first?  

Regards
Luca

**Comment by MaartenGr** [comment]
It seems that you are using an older version of KeyBERT. I would advise upgrading KeyBERT with: `pip install --upgrade keybert`. That should solve your issue.

**Comment by lfoppiano** [comment]
@MaartenGr Thanks! Indeed that was the issue. For information, I installed keybert using `pip install keybert[all]` I have no idea why it picked up the version 0.1.3.
