### ISSUE TITLE
Misleading output when using highlight=True

### ISSUE THREAD

**Issue by DavidFarago** [MaartenGr/KeyBERT#65]
Since KeyBERT's approach seems sufficiently similar to https://link.springer.com/chapter/10.1007/978-981-15-7984-4_8, I thought it might yield good results on short text, too.

I tried `all-MiniLM-L6-v2` on English and `paraphrase-multilingual-MiniLM-L12-v2` on German short text and did not get satisfying results, e.g. 
* "Do you **currently** have ailments?" instead of "Do you currently have **ailments**?" 
* "Do you have **visual** problems?" instead of " Do you have **visual problems**?"
* "**Leiden Sie** an einer Herzerkrankung?" instead of "Leiden Sie an einer **Herzerkrankung**?"
* "Haben Sie **derzeit** Beschwerden?" instead of "Haben Sie derzeit **Beschwerden**?" 
with keywords marked **bold**.

Is KeyBERT capable of extracting keywords from short text? In both English and German? Which models do I have to use? Or do I have to train my own?

**Comment by DavidFarago** [comment]
When I do not use `highlight=True`, I get the following:

```
[('herzerkrankung', 0.2899), ('leiden', 0.1449), ('sie', 0.092), ('einer', 0.0867)]
[('bluthochdruck', 0.5784), ('leiden', 0.0998), ('sie', 0.0677)]
[('diabetes', 0.7602), ('zucker', 0.4794), ('leiden', 0.068), ('sie', 0.0399)]
[('insulin', 0.7074), ('metformin', 0.5114), ('benötigen', 0.2534), ('oder', 0.2079), ('und', 0.1742)]
[('asthma', 0.7798), ('lungenerkrankung', 0.7421), ('leiden', 0.1248), ('einer', 0.089), ('sie', 0.0832)]
[('gewicht', 0.5544), ('verloren', 0.3992), ('haben', 0.2194), ('ungewollt', 0.1415), ('sie', 0.0886)]
[('vorname', 0.4119)]
[('beschwerden', 0.6105), ('derzeit', 0.3824), ('haben', 0.3145), ('aktuelle', 0.3036), ('sie', 0.1623)]
[('beschwerden', 0.4591), ('ja', 0.2397), ('wenn', 0.2118), ('aktuellen', 0.2023), ('welche', 0.1276)]
[('allergien', 0.6857), ('hauterkrankungen', 0.4097), ('bekannt', 0.1579), ('oder', 0.147), ('sind', 0.1251)]
[('allergien', 0.588), ('hauterkrankungen', 0.4316), ('oder', 0.1555), ('ja', 0.1277), ('wenn', 0.1151)]
[('stoffen', 0.5035), ('desinfektionsmittel', 0.457), ('spülmittel', 0.3874), ('kühlschmiermittel', 0.3816), ('beruflich', 0.3255)]
```
:)

**Comment by MaartenGr** [comment]
Ah yes, so the algorithm gives back a certain number of top keywords and highlights all of them. The output between `highlight=True` and `highlight=False` is exactly the same. The highlighting itself is different since it cannot highlight all keywords if, for example, stopwords are removed.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. If you want to discuss this issue further, let me know and I'll reopen the issue!
