### ISSUE TITLE
No keyword found for short text 'Name'

### ISSUE THREAD

**Issue by DavidFarago** [MaartenGr/KeyBERT#69]
I tried KeyBERT on various short text, e.g. 'birth' or 'E-Mail', and usually it does extract the single word as keyword.

However, for 'Name' KeyBERT returns an empty list:

```
import sys
from keybert import KeyBERT

kw_model = KeyBERT(model='paraphrase-multilingual-MiniLM-L12-v2')
print(kw_model.extract_keywords('Name', stop_words=None))
```

Why does KeyBERT not extract the keyword 'Name' for the input 'Name'?

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Let me know if you are still experiencing this issue and I'll make sure to reopen the issue!
