### ISSUE TITLE
GensimBackend

### ISSUE THREAD

**Issue by lixiepeng** [MaartenGr/KeyBERT#71]
`AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0.
Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead.
See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4`

**Comment by MaartenGr** [comment]
Could you share how you have initialized the model? Also, which version of KeyBERT and Gensim are you using?

**Comment by MaartenGr** [comment]
The last response has been a while ago, so I'll be closing this issue for now. Having said that, let me know if you are still experiencing this issue and I'll make sure to reopen it.

**Comment by dopc** [comment]
I have faced with the same problem,

how I have initialized the model:

```
import gensim.downloader as api
from keybert import KeyBERT

ft = api.load('fasttext-wiki-news-subwords-300')
kw_model = KeyBERT(model=ft)
```

the versions I am using:
```
gensim==4.2.0
keybert==0.6.0
```

BR.

**Comment by MaartenGr** [comment]
@dopc The way Gensim accesses the embeddings in 4.0 was chanced and not yet updated in KeyBERT. For now, using Gensim < 4.0 should work without any issues. I'll make sure it gets updated in the upcoming released.

**Comment by dopc** [comment]
Thanks so much!
