### ISSUE TITLE
Option to disable tqdm

### ISSUE THREAD

**Issue by christopherfeld** [MaartenGr/KeyBERT#72]
When running lots of docs, it would be nice to have an option to disable.

**Comment by MaartenGr** [comment]
Could you share how you are exactly using KeyBERT? From my understanding, tqdm will not run if you process one document at a time. I might be mistaken though!

**Comment by christopherfeld** [comment]
I'm doing a looping function to process each document at a time. 

A simple work around is to run the process as .py so the printout doesn't consume my browser resources.

**Comment by MaartenGr** [comment]
If I run the following, no tqdm bar is generated when creating the keywords:

```python
from keybert import KeyBERT

doc = """
         Supervised learning is the machine learning task of learning a function that
         maps an input to an output based on example input-output pairs. It infers a
         function from labeled training data consisting of a set of training examples.
         In supervised learning, each example is a pair consisting of an input object
         (typically a vector) and a desired output value (also called the supervisory signal). 
         A supervised learning algorithm analyzes the training data and produces an inferred function, 
         which can be used for mapping new examples. An optimal scenario will allow for the 
         algorithm to correctly determine the class labels for unseen instances. This requires 
         the learning algorithm to generalize from the training data to unseen situations in a 
         'reasonable' way (see inductive bias).
      """
kw_model = KeyBERT()

for i in range(100):
    keywords = kw_model.extract_keywords(doc)
```

The tqdm bar is only generated when `doc` is not a string but a list of strings. Although a list of strings may speed things up you cannot use MMR and MaxSumSim using that method. I would advise processing a single document at a time.

**Comment by christopherfeld** [comment]
Ah yes, turns out it was the transform method on BERTopic (I'm using both in a particular use case so got my wires crossed!).
