### ISSUE TITLE
OverflowError: int too big to convert

### ISSUE THREAD

**Issue by ericxsun** [MaartenGr/KeyBERT#76]
with the following code (keybert=v0.5), I met `OverflowError: int too big to convert`:

```python
from keybert import KeyBERT
from flair.embeddings import TransformerDocumentEmbeddings
roberta = TransformerDocumentEmbeddings('hfl/rbtl3')
kw_model = KeyBERT(model=roberta)

doc = """
         Supervised learning is the machine learning task of learning a function that
         maps an input to an output based on example input-output pairs. It infers a
         function from labeled training data consisting of a set of training examples.
         In supervised learning, each example is a pair consisting of an input object
         (typically a vector) and a desired output value (also called the supervisory signal). 
         A supervised learning algorithm analyzes the training data and produces an inferred function, 
         which can be used for mapping new examples. An optimal scenario will allow for the 
         algorithm to correctly determine the class labels for unseen instances. This requires 
         the learning algorithm to generalize from the training data to unseen situations in a 
         'reasonable' way (see inductive bias).
      """

kw_model.extract_keywords(doc, highlight=True)
```

however, with model `roberta-base`, I got the correct things
![image](https://user-images.githubusercontent.com/1772912/140482624-7d1ea5fc-7ff4-498a-a0df-63fd9e20f465.png)

**Comment by MaartenGr** [comment]
This might happen depending on the model that you are using. I believe this might be due to the model not having the `model_max_length` set. This might solve your issue:

```python
roberta = TransformerDocumentEmbeddings('hfl/rbtl3', model_max_length=512)
```

or: 

```python
roberta = TransformerWordEmbeddings('hfl/rbtl3', model_max_length=512)
```

if that param only works with the word embeddings.

**Comment by ericxsun** [comment]
> This might happen depending on the model that you are using. I believe this might be due to the model not having the `model_max_length` set. This might solve your issue:
> 
> ```python
> roberta = TransformerDocumentEmbeddings('hfl/rbtl3', model_max_length=512)
> ```
> 
> or:
> 
> ```python
> roberta = TransformerWordEmbeddings('hfl/rbtl3', model_max_length=512)
> ```
> 
> if that param only works with the word embeddings.

Thanks very much
