### ISSUE TITLE
Spanish and other languages

### ISSUE THREAD

**Issue by rdpulgar** [MaartenGr/KeyBERT#8]
Hi,
Just want to know if KeyBert works in spanish. Can I change the BERT model to one that is suitable for spanish?

Thank you

**Comment by MaartenGr** [comment]
Yes! There are many transformer models that you can use. You can find the full overview of models [here](https://www.sbert.net/docs/pretrained_models.html). In your case, to make it work in Spanish, we select the `xlm-r-bert-base-nli-stsb-mean-tokens` model as it has been trained for 50+ languages. 

To do this, simply replace:

```python
model = KeyBERT('distilbert-base-nli-mean-tokens')
```

with: 

```python
model = KeyBERT('xlm-r-bert-base-nli-stsb-mean-tokens')
```

And that is it! Now you can use it for Spanish. You can play around with some of the models to get a feeling which is best for your application.

**Comment by rdpulgar** [comment]
Thank you. I made some successful tests.
