### ISSUE TITLE
TypeError extract_keywords() got an unexpected keyword argument 'highlight'

### ISSUE THREAD

**Issue by TeTeTang** [MaartenGr/KeyBERT#89]
Just got a "TypeError extract_keywords() got an unexpected keyword argument 'highlight'" by running the example of highlighting the keywords.

**Comment by MaartenGr** [comment]
Which version of KeyBERT are you running? I believe making sure you have the most recent version installed may fix your issue.

**Comment by TeTeTang** [comment]
I'm using the latest version 0.5.0, that doesn't resolve the issue.

**Comment by TeTeTang** [comment]
Signature:
kw_model.extract_keywords(
    docs: Union[str, List[str]],
    candidates: List[str] = None,
    keyphrase_ngram_range: Tuple[int, int] = (1, 1),
    stop_words: Union[str, List[str]] = 'english',
    top_n: int = 5,
    min_df: int = 1,
    use_maxsum: bool = False,
    use_mmr: bool = False,
    diversity: float = 0.5,
    nr_candidates: int = 20,
    vectorizer: sklearn.feature_extraction.text.CountVectorizer = None,
) -> Union[List[Tuple[str, float]], List[List[Tuple[str, float]]]]

**Comment by MaartenGr** [comment]
Based on the parameters it does seem like you have an earlier version installed. Could you start from a fresh environment and install the latest version there? Perhaps something went wrong with upgrading KeyBERT.
