### ISSUE TITLE
training model

### ISSUE THREAD

**Issue by mrnomanrazashah** [MaartenGr/KeyBERT#91]
Hello Sir.
Thank you so much for providing this great tool.
How to train the KeyBERT model on customized datasets?

**Comment by MaartenGr** [comment]
You do not have to train KeyBERT on customized datasets as it uses pre-trained language models to create the embedding procedures. The main challenge here is finding a language model that fits with your data. However, you can typically start with the default model in KeyBERT as that already works quite well across a variety of datasets.

**Comment by mrnomanrazashah** [comment]
Alright and Thank you so much for the fast response.

**Comment by MaartenGr** [comment]
No problem, glad I could be of help :)
