### ISSUE TITLE
Maxsum returns wrong similarlities

### ISSUE THREAD

**Issue by kunihik0** [MaartenGr/KeyBERT#92]
Hi, thank you for good KeyBert! 
I think the method of getting the distance by index in _maxsum.py is wrong . The problem is that the similarity between the sentence and the candidate is specified with a different index than the actual one, so the wrong similarity is returned.
I think the following points need to be changed.

`return [(words_vals[idx], round(float(distances[0][idx]), 4)) for idx in candidate]`
to
`return [(words_vals[idx], round(float(distances[0][words_idx[idx]]), 4)) for idx in candidate]`

https://github.com/MaartenGr/KeyBERT/blob/master/keybert/_maxsum.py#:~:text=return%20%5B(words_vals%5Bidx%5D%2C%20round(float(distances%5B0%5D%5Bidx%5D)%2C%204))%20for%20idx%20in%20candidate%5D

**Comment by MaartenGr** [comment]
Sorry for the late response and thank you for tracking this down! I'll make sure it gets fixed in the next release.

**Comment by MaartenGr** [comment]
Thank you for the pull request! It was merged and will be added in the next pypi release.

**Comment by kunihik0** [comment]
Thanks for checking and merging!
